### ISSUE TITLE
manage.py not working

### ISSUE THREAD

**Issue by prateethvnayak** [tbags/django-image-annotation-tool#2]
`python manage.py syncdb` 

SyntaxError : Generator expression must be parenthesized

virtual env:
- Python3.7
Dependencies - installed using `requirements.txt`

**Comment by tbags** [comment]
@prateethvnayak: So you are required to build your environment with python3.6 and not 3.7(follow [this guide](https://github.com/tbags/django-image-annotation-tool#setup)). I'd first give that a try, also, next time please put the entire stack trace, so that we know where the exception is raised. Thanks.

**Comment by prateethvnayak** [comment]
@tbags 
Changed to virtualenv with python3.6.4_2 (homebrew dist) 

`python manage.py syncdb` 

Output: (entire traceback)
`
Unknown command: 'syncdb'
Type 'manage.py help' for usage.
(Annotator) 
`

_syncdb_ not a subcommand of `manage.py`
I guess the guide needs to be updated. 
`python manage.py help` does not show such a subcommand either.

**Comment by tbags** [comment]
Ah! I see, could you try skipping the syncdb. I think the base db is already committed to this patch.

**Comment by prateethvnayak** [comment]
Oh okay. Got it running. Thanks @tbags

**Comment by tbags** [comment]
https://github.com/tbags/django-image-annotation-tool/commit/5a841f2a38b66ede857863d75d75c94618bf0a91
